# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print("method 1 \n", a)

method 1 
 [[[0.89439822 0.44298712 0.40682551 0.83750497 0.85010173]
  [0.47508985 0.42971535 0.55121275 0.01875059 0.85731748]
  [0.38976541 0.88906324 0.72662552 0.10508558 0.77071254]]

 [[0.24073236 0.66073398 0.19270361 0.07346093 0.28016006]
  [0.27360489 0.36571405 0.67122264 0.90709843 0.19529242]
  [0.8598369  0.15161691 0.15751548 0.34835567 0.26417692]]]


In [4]:
# Method 2
a = np.random.random(size = (2,3,5))
print("method 2 \n", a)

method 2 
 [[[0.46856784 0.78587614 0.73803772 0.0580735  0.85105374]
  [0.68973469 0.40353477 0.84088354 0.15673607 0.56761758]
  [0.13605131 0.11978332 0.95565317 0.09194671 0.18386999]]

 [[0.60790106 0.02394601 0.92640727 0.96587035 0.07566135]
  [0.54426621 0.14259109 0.23568481 0.08644305 0.73637068]
  [0.33425255 0.5511262  0.09906277 0.13794699 0.18110494]]]


In [5]:
# Method 3
a = np.random.random([2,3,5])
print("method 3 \n", a)

method 3 
 [[[0.7354904  0.07889871 0.96086133 0.64234364 0.53781385]
  [0.51695791 0.57985939 0.41520774 0.76149942 0.26256269]
  [0.42128007 0.86654304 0.11860127 0.46057247 0.81766655]]

 [[0.77410974 0.13875033 0.70697525 0.63361915 0.82056115]
  [0.4171128  0.83846527 0.10175054 0.41322289 0.15578966]
  [0.32774661 0.13392704 0.25506656 0.48484311 0.17959371]]]


#### 4. Print *a*.


In [6]:
# your code here
#This is what they wanted to hear:
a1 = np.random.randint(10, size = (2,3,5));
a2 = np.random.rand(2,3,5);
a3 = np.random.random((2,3,5));

print("a1 is: \n", a1, "\n")
print("a2 is: \n", a2, "\n")
print("a3 is: \n", a3, "\n")

a1 is: 
 [[[9 9 7 8 0]
  [3 8 2 8 2]
  [8 5 2 3 8]]

 [[8 9 5 3 8]
  [8 5 7 2 1]
  [6 6 9 5 6]]] 

a2 is: 
 [[[0.31394268 0.55343776 0.54340618 0.22886727 0.35130297]
  [0.60807809 0.05492105 0.4232501  0.8459997  0.21733852]
  [0.40476996 0.22233668 0.84144995 0.14207624 0.87614011]]

 [[0.27156755 0.9074277  0.67507421 0.87297702 0.60642235]
  [0.87506259 0.40288803 0.33153418 0.04908308 0.3887417 ]
  [0.53348957 0.82129944 0.99235647 0.09948778 0.31159806]]] 

a3 is: 
 [[[0.81748122 0.56104598 0.70008303 0.84216656 0.05442567]
  [0.36426988 0.84246953 0.56546175 0.07544853 0.18426177]
  [0.71956629 0.24290632 0.29190297 0.30072081 0.0601522 ]]

 [[0.27629714 0.56111989 0.70431119 0.5194643  0.99198692]
  [0.25406599 0.59117978 0.93239746 0.01939177 0.29322726]
  [0.36658534 0.01363642 0.91208871 0.59788431 0.84458665]]] 



#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
# Yes, as 5*2*3 = 2*3*5

print("check option 1:", a.size == b.size)
print("check option 2: \n The size of a is:", a.size,"\n The size of b is:", b.size)


check option 1: True
check option 2: 
 The size of a is: 30 
 The size of b is: 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
#No, because the dimensions are differently shaped

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
# a: 2, 3, 5
# b: 5, 2, 3
c = np.transpose(b, [1, 2, 0]); 
# put the number at index 1 on the spot of index 0; the number at index 2 on the spot of index 1 and index 0 on the last index (2)
print ("this is c \n", c)


this is c 
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a,c)
print (d)
#it works because they are of the same shape (there is always a 'counterpart' present in the other array)

[[[1.7354904  1.07889871 1.96086133 1.64234364 1.53781385]
  [1.51695791 1.57985939 1.41520774 1.76149942 1.26256269]
  [1.42128007 1.86654304 1.11860127 1.46057247 1.81766655]]

 [[1.77410974 1.13875033 1.70697525 1.63361915 1.82056115]
  [1.4171128  1.83846527 1.10175054 1.41322289 1.15578966]
  [1.32774661 1.13392704 1.25506656 1.48484311 1.17959371]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print (a)
print (d)

# they are the same, but in d  1 is added to each element in a

[[[0.7354904  0.07889871 0.96086133 0.64234364 0.53781385]
  [0.51695791 0.57985939 0.41520774 0.76149942 0.26256269]
  [0.42128007 0.86654304 0.11860127 0.46057247 0.81766655]]

 [[0.77410974 0.13875033 0.70697525 0.63361915 0.82056115]
  [0.4171128  0.83846527 0.10175054 0.41322289 0.15578966]
  [0.32774661 0.13392704 0.25506656 0.48484311 0.17959371]]]
[[[1.7354904  1.07889871 1.96086133 1.64234364 1.53781385]
  [1.51695791 1.57985939 1.41520774 1.76149942 1.26256269]
  [1.42128007 1.86654304 1.11860127 1.46057247 1.81766655]]

 [[1.77410974 1.13875033 1.70697525 1.63361915 1.82056115]
  [1.4171128  1.83846527 1.10175054 1.41322289 1.15578966]
  [1.32774661 1.13392704 1.25506656 1.48484311 1.17959371]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a,c)
print (e)

[[[0.7354904  0.07889871 0.96086133 0.64234364 0.53781385]
  [0.51695791 0.57985939 0.41520774 0.76149942 0.26256269]
  [0.42128007 0.86654304 0.11860127 0.46057247 0.81766655]]

 [[0.77410974 0.13875033 0.70697525 0.63361915 0.82056115]
  [0.4171128  0.83846527 0.10175054 0.41322289 0.15578966]
  [0.32774661 0.13392704 0.25506656 0.48484311 0.17959371]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

#Yes, as a is only multiplied by 1 it remains the same

a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print (d_max, d_min, d_mean)

1.9608613344506467 1.0788987143581494 1.4852564098614474


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))
print(f)

#beter gebruik np.zeros dan weet je tenminste dat het daar vandaan komt. (alleen empty is iets sneller)

[[[0.7354904  0.07889871 0.96086133 0.64234364 0.53781385]
  [0.51695791 0.57985939 0.41520774 0.76149942 0.26256269]
  [0.42128007 0.86654304 0.11860127 0.46057247 0.81766655]]

 [[0.77410974 0.13875033 0.70697525 0.63361915 0.82056115]
  [0.4171128  0.83846527 0.10175054 0.41322289 0.15578966]
  [0.32774661 0.13392704 0.25506656 0.48484311 0.17959371]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

print(d.shape)
# d equals two series of 3 rows with each 5 values. So you have 3 levels (i, j , k) with a range of 2, 3 or 5

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i][j][k] > d_min and i < d_mean: #iterates through all possible positiosn, 0-0-0 '0-0-1' all the way to 2-3-5
                f[i][j][k] = (25)
            if d[i][j][k] > d_mean and i < d_max:
                f[i][j][k] = (75)
            if d[i][j][k] == d_mean:
                f[i][j][k] = (50)
            if d[i][j][k] == d_min:
                f[i][j][k] = (0)
            if d[i][j][k] == d_max:
                f[i][j][k] = (100)
                                
print(f)

#the answer from the solutions looks very complicated to me

(2, 3, 5)
[[[ 75.   0. 100.  75.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  75.  25.  25.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [22]:
# your code here
print("This is D: \n", d)

print("This is F: \n", f)

print("Seems oke")

This is D: 
 [[[1.7354904  1.07889871 1.96086133 1.64234364 1.53781385]
  [1.51695791 1.57985939 1.41520774 1.76149942 1.26256269]
  [1.42128007 1.86654304 1.11860127 1.46057247 1.81766655]]

 [[1.77410974 1.13875033 1.70697525 1.63361915 1.82056115]
  [1.4171128  1.83846527 1.10175054 1.41322289 1.15578966]
  [1.32774661 1.13392704 1.25506656 1.48484311 1.17959371]]]
This is F: 
 [[[ 75.   0. 100.  75.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  75.  25.  25.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]]
Seems oke


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
f_letter = np.empty((2,3,5), dtype='U1')

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i][j][k] > d_min and i < d_mean: #iterates through all possible positiosn, 0-0-0 '0-0-1' all the way to 2-3-5
                f_letter[i][j][k] = ('A')
            if d[i][j][k] > d_mean and i < d_max:
                f_letter[i][j][k] = ('B')
            if d[i][j][k] == d_mean:
                f_letter[i][j][k] = ('C')
            if d[i][j][k] == d_min:
                f_letter[i][j][k] = ('D')
            if d[i][j][k] == d_max:
                f_letter[i][j][k] = ('E')
                                
print(f_letter)

[[['B' 'D' 'E' 'B' 'B']
  ['B' 'B' 'A' 'B' 'A']
  ['A' 'B' 'A' 'A' 'B']]

 [['B' 'A' 'B' 'B' 'B']
  ['A' 'B' 'A' 'A' 'A']
  ['A' 'A' 'A' 'A' 'A']]]
